name: main

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # PASSO CRÍTICO: Decodifica o segredo e salva com o nome que o Python exige (hxh.json)
      - name: Criar credencial Google (hxh.json)
        run: echo "${{ secrets.GCP_SA_KEY_JSON }}" | base64 -d > hxh.json

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps

      - name: Executar o script
        # xvfb-run é obrigatório pois seu script usa headless=False
        run: xvfb-run python main.py
